### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by RamseyNjire**
Here you will find our implementation of some of the methods in the Ruby Enumerable module. We look forward to your comments and suggestions.

### CODE REVIEW

**Review by adaorachi — COMMENTED** [review]
### Hi @RamseyNjire  and @mimipeshy, :wave: 

Well done on the completion of the first draft of this project but sadly I cannot review the project because it did not meet the required Git flow guidelines which states thus;

- [ ] Ensure that you work with Git Flow: production master branch + main development branch + Pull Requests from feature branches. Do not work directly in the development branch. Create a feature-branch branch (give it a descriptive name) and open a Pull Request from it to the development branch. When your feature is ready and Pull request approved, you can merge it to the development branch. 
Here is the [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/git_flow.png) from pathwright  and a [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421589/) to the project requirement. Kindly read through the "**Remember to**" section for further clarification.

---
I'm sorry to inform you that this project will be marked as **INVALID**. Kindly modify your project to meet the above description and when it is done, you can request for another review by submitting a code review form.

### STATUS: INVALID 
---

**Should you have any question, please feel free with reach out to me on Slack with the username - adaorachi.**

**Happy Coding! :relaxed:** 

**MaryAnn Chukwuka**

**Comment by RamseyNjire** [comment]
Hey, MaryAnne! We did use the Git flow workflow. We followed exactly as this article (https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), which was recommended in Pathwright, indicates. I installed git flow locally and used it to create feature branches locally. I would use the command 

`git flow feature start feature_branch`

to start the feature branch and

`git flow feature finish feature_branch`

to finish the feature. 

the article seemed to indicate that features should be developed locally then pushed to the 'develop' branch at Origin.

I'm not sure where I went wrong. Perhaps I misunderstood?

**Comment by RamseyNjire** [comment]
Also, I have already tried to make a feature_branch to merge into develop, and that doesn't work, as there is nothing to compare. I could show you our commit history to prove that we have employed git flow. I'm not sure what we're missing...

**Comment by adaorachi** [comment]
Hi Ramsey, please can you give me some minutes to reply to your comments properly, to help you out and share some screenshots with you. I'm currently using my mobile device as my PC is running some installations and i cannot use it at the moment.

**Comment by RamseyNjire** [comment]
Sure thing, MaryAnne!

**Comment by adaorachi** [comment]
### **Hello team 👋** 

This is to let you know that I am aware that the code review you submitted for this pull request was made by oversight and that you have made the necessary changes to correct the issue raised in the previous review. This review will also be marked as invalid. 

**STATUS: INVALID** 

Please kindly ensure to submit another code review form with the updated Pull Request URL.

Happy Coding ☺️ 

**MaryAnn Chukwuka.**

**Pull request closed without merging**
